version: '3.8'

services:

  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nikifor -d shorten" ]
      interval: 3s
      timeout: 3s
      retries: 3

    environment:
      DB_PASS: "1234"

  redis:
    image: redis:6
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


volumes:
  postgres_data:
  redis_data: