CREATE USER nikifor WITH PASSWORD '1234';
ALTER USER nikifor WITH SUPERUSER;
CREATE DATABASE shorten OWNER nikifor;
GRANT CONNECT ON DATABASE shorten TO nikifor;
GRANT CREATE ON SCHEMA public TO nikifor;