"""add expires and alias

Revision ID: 1697a9caafaf
Revises: 13d9e514f59c
Create Date: 2025-03-24 17:00:27.883369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1697a9caafaf'
down_revision: Union[str, None] = '13d9e514f59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('custom_alias', sa.String(), nullable=True))
    op.add_column('links', sa.Column('expires_at', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'links', ['custom_alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    op.drop_column('links', 'expires_at')
    op.drop_column('links', 'custom_alias')
    # ### end Alembic commands ###
