"""add shorten nullable

Revision ID: 380b73b09d73
Revises: 1697a9caafaf
Create Date: 2025-03-24 21:33:42.981315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380b73b09d73'
down_revision: Union[str, None] = '1697a9caafaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'short_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'short_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
